# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "A replicated Apache Pekko Persistence journal backed by Apache Cassandra"
  homepage: https://pekko.apache.org/
  labels:
    - pekko
    - pekko-persistence
    - java
    - scala
    - cqrs
    - cassandra
    - eventsourcing
  
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: false
